"""added column for sesnor class (imei and source_name)

Revision ID: 116309d3209a
Revises: 4a5378490125
Create Date: 2023-09-08 14:24:59.997958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116309d3209a'
down_revision = '4a5378490125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imei', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('source_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('source_name')
        batch_op.drop_column('imei')

    # ### end Alembic commands ###
