"""added all columns for sensors -longitude was missing

Revision ID: 85a603e73bb2
Revises: 81ec97dfb185
Create Date: 2023-09-09 11:15:20.974523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a603e73bb2'
down_revision = '81ec97dfb185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_longitude', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('latest_longitude')

    # ### end Alembic commands ###
